#==========================================
# Five Band Dynamic Range Compression
# Author: Tahsin A Chowdhury
# Last modification:   Dec. 2020 (by Nasim Alamdari)
#==========================================


function [compressed_audio, unCompressed_audio] = DRCFiveBand(signal, Fs, data, slope) % data contains compression settinhs including compresion rate, attack time, etc.

persistent crossover
persistent crossOverFreq
% Persistent variables are local to the function in which they are declared,
% yet their values are retained in memory between calls to the function.

if (isempty(crossOverFreq))
    crossOverFreq = [ 500 1000 2000 4000 ]; %
    %[375,1125,2250,4500]% for midfreq [250,750,1500,3000,6000]
    %[375, 625, 875, 1250, 1750, 2500, 3500, 5000] % for midfreq [250, 500,750,1000,1500,2000,3000,4000,6000]
end

num_crossover = length(crossOverFreq);
if(isempty(crossover))
    crossover = crossoverFilter(num_crossover, ...
        crossOverFreq, slope ,'SampleRate',Fs);
end

%visualize(crossover)
%% to split sigal to different frequency bands
[y1, y2, y3, y4, y5] = crossover(signal);

%% Design and Apply DRC compression
%persistent dRC1 dRC2 dRC3 dRC4 dRC5
%if (isempty(dRC1)) % performing compression for each band
    dRC1 = compressor('SampleRate',Fs, ...
        'Ratio',data(1,1), ...
        'Threshold',data(1,2), ...
        'KneeWidth',5, ...
        'AttackTime',data(1,3), ...
        'ReleaseTime',data(1,4),...
        'MakeUpGainMode','property',...
        'MakeUpGain', data(1,5));
%end


%if (isempty(dRC2))
    dRC2 = compressor('SampleRate',Fs, ...
        'Ratio',data(2,1), ...
        'Threshold',data(2,2), ...
        'KneeWidth',5, ...
        'AttackTime',data(2,3), ...
        'ReleaseTime',data(2,4),...
        'MakeUpGainMode','property',...
        'MakeUpGain', data(2,5));
%end

%if (isempty(dRC3))
    dRC3 = compressor('SampleRate',Fs, ...
        'Ratio',data(3,1), ...
        'Threshold',data(3,2), ...
        'KneeWidth',5, ...
        'AttackTime',data(3,3), ...
        'ReleaseTime',data(3,4),...
        'MakeUpGainMode','property',...
        'MakeUpGain', data(3,5));
%end

%if (isempty(dRC4))
    dRC4 = compressor('SampleRate',Fs, ...
        'Ratio',data(4,1), ...
        'Threshold',data(4,2), ...
        'KneeWidth',5, ...
        'AttackTime',data(4,3), ...
        'ReleaseTime',data(4,4),...
        'MakeUpGainMode','property',...
        'MakeUpGain', data(4,5));
%end

%if (isempty(dRC5))
    dRC5 = compressor('SampleRate',Fs, ...
        'Ratio',data(5,1), ...
        'Threshold',data(5,2), ...
        'KneeWidth',5, ...
        'AttackTime',data(5,3), ...
        'ReleaseTime',data(5,4),...
        'MakeUpGainMode','property',...
        'MakeUpGain', data(5,5));
%end

a1 = dRC1(y1);
a2 = dRC2(y2);
a3 = dRC3(y3);
a4 = dRC4(y4);
a5 = dRC5(y5);

% New audio output
compressed_audio = a1+a2+a3+a4+a5;
unCompressed_audio = y1+y2+y3+y4+y5;

end

